# Generated by Django 3.0.3 on 2020-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seekerprofiles', '0003_auto_20200714_1336'),
        ('donorprofiles', '0006_donorprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=150)),
                ('points_cost', models.IntegerField()),
                ('donors', models.ManyToManyField(blank=True, related_name='bought_tests', to='donorprofiles.DonorProfile')),
                ('seekers', models.ManyToManyField(blank=True, related_name='offered_tests', to='seekerprofiles.SeekerProfile')),
            ],
        ),
    ]
