# Generated by Django 3.0.3 on 2020-07-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seekerprofiles', '0001_initial'),
        ('offeredtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredtest',
            name='seeker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_tests', to='seekerprofiles.SeekerProfile'),
        ),
    ]
