# Generated by Django 3.0.3 on 2020-07-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodrequests', '0001_initial'),
        ('donorprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_to_requests', to='donorprofiles.DonorProfile'),
        ),
    ]
