# Generated by Django 3.0.3 on 2020-07-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donorprofiles', '0001_initial'),
        ('seekerprofiles', '0001_initial'),
        ('bloodrequests', '0002_bloodrequest_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_requests', to='seekerprofiles.SeekerProfile'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='selected_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_requests', to='donorprofiles.DonorProfile'),
        ),
    ]
