# Generated by Django 3.0.3 on 2020-07-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequests', '0003_auto_20200715_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='until',
            field=models.DateField(),
        ),
    ]
