# Generated by Django 3.0.3 on 2020-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequests', '0004_auto_20200715_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='is_for_covid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='is_renewable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='is_urgent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('COM', 'Completed')], max_length=4),
        ),
    ]
