# Generated by Django 3.0.3 on 2020-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequests', '0005_auto_20200715_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('COM', 'Completed')], default='OP', max_length=4),
        ),
    ]
