# Generated by Django 3.0.3 on 2020-07-14 11:09

import apps.registrations.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@email.com', max_length=254, unique=True)),
                ('code', models.CharField(default=apps.registrations.models.code_generator, max_length=5)),
                ('code_type', models.CharField(choices=[('RVC', 'Registration Validation Code'), ('PRC', 'Password Reset Code')], max_length=3)),
                ('code_expiration', models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 9, 48, 967054, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
