# Generated by Django 3.0.3 on 2020-07-16 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20200716_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 44, 22, 520237, tzinfo=utc)),
        ),
    ]
