# Generated by Django 3.0.3 on 2020-07-15 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20200715_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 53, 42, 796320, tzinfo=utc)),
        ),
    ]
