# Generated by Django 3.0.3 on 2020-07-14 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20200714_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 20, 4, 0, 637033, tzinfo=utc)),
        ),
    ]
