# Generated by Django 3.0.3 on 2020-07-14 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20200714_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 14, 3, 22, 100207, tzinfo=utc)),
        ),
    ]
