# Generated by Django 3.0.3 on 2020-07-15 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20200714_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 7, 34, 56, 36543, tzinfo=utc)),
        ),
    ]
