# Generated by Django 3.0.3 on 2020-07-17 07:09

import apps.registrations.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_valid', models.BooleanField(default=True)),
                ('name', models.CharField(default='name', max_length=100)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('code', models.CharField(default=apps.registrations.models.code_generator, max_length=5)),
            ],
        ),
    ]
