# Generated by Django 3.0.3 on 2020-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerprofiles', '0002_seekerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='zip',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
