# Generated by Django 3.0.3 on 2020-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerprofiles', '0002_seekerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
