# Generated by Django 3.0.3 on 2020-07-14 13:36

import apps.registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerprofiles', '0002_auto_20200714_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='code',
            field=models.CharField(default=apps.registrations.models.code_generator, max_length=5),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='zip',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
