# Generated by Django 3.0.3 on 2020-07-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerprofiles', '0003_auto_20200714_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekerprofile',
            old_name='certificates',
            new_name='certificate',
        ),
    ]
