
// Login types

export const USER_LOGIN = 'USER_LOGIN'
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'

// Logout types

export const USER_LOGOUT = 'USER_LOGOUT'


// ErrorComponent Types

export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// Search Types

export const SET_USER_PROFILES = 'SET_USER_PROFILES'
export const SET_RESTAURANTS = 'SET_RESTAURANTS'
export const SET_REVIEWS = 'SET_REVIEWS'
export const CHANGE_SEARCH_TAB_INDEX = 'CHANGE_SEARCH_TAB_INDEX'
export const RESET_SEARCH = 'RESET_SEARCH'

// User Profile Types

export const SET_USER_PROFILE_REVIEWS = 'SET_USER_PROFILE_REVIEWS'
export const SET_USER_PROFILE_RESTAURANTS = 'SET_USER_PROFILE_RESTAURANTS'
export const SET_USER_PROFILE_COMMENTS = 'SET_USER_PROFILE_COMMENTS'
export const SET_USER_PROFILE_USER = 'SET_USER_PROFILE_USER'

