# Generated by Django 3.0.3 on 2020-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorprofiles', '0002_donorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(choices=[('O', 'O'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='O-', max_length=3),
        ),
    ]
