# Generated by Django 3.0.3 on 2020-07-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorprofiles', '0002_donorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='last_donation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
