# Generated by Django 3.0.3 on 2020-07-14 12:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donorprofiles', '0002_auto_20200714_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
