# Generated by Django 3.0.3 on 2020-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorprofiles', '0003_auto_20200715_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='zip',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
