# Generated by Django 3.0.3 on 2020-07-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorprofiles', '0005_auto_20200714_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('0', 'other')], default='M', max_length=2),
        ),
    ]
